import { Router } from "express";
import {
  db,
  customerRfqsTable,
  customerRfqItemsTable,
  customersTable,
  employeesTable,
  rfqItemsTable,
  offerItemsTable,
  auditLogTable,
} from "@workspace/db";
import { eq, ilike, count, inArray, desc, and, isNull, or } from "drizzle-orm";
import { requireAuth } from "../../middlewares/auth";

const router = Router();

// VAT rate — must match the rfq module (used to normalize tax-inclusive
// supplier prices to excl-tax for the margin check).
const VAT_RATE = 0.14;
// Required margin: the customer price (excl tax) must be at least this factor
// times the approved supplier price (excl tax) — prevents pricing at a loss.
const MARGIN_FACTOR = 1.06;

// For each customer RFQ item, resolve the approved supplier price (excl tax)
// via the rfq_items.customer_rfq_item_id link, falling back to partNo/lineItem
// matching for legacy supplier RFQs that lack the FK link. Returns a map
// customerItemId -> { costExclTax (min approved) | null, hasApproved }.
async function resolveApprovedCosts(
  customerItems: Array<{ id: number; partNo: string | null; lineItem: string | null }>,
): Promise<Map<number, number | null>> {
  const result = new Map<number, number | null>();
  if (customerItems.length === 0) return result;

  const ids = customerItems.map((i) => i.id);
  // Approved offer items linked directly via the FK.
  const linked = await db
    .select({
      customerRfqItemId: rfqItemsTable.customerRfqItemId,
      price: offerItemsTable.price,
      taxIncluded: offerItemsTable.taxIncluded,
    })
    .from(offerItemsTable)
    .innerJoin(rfqItemsTable, eq(offerItemsTable.rfqItemId, rfqItemsTable.id))
    .where(and(inArray(rfqItemsTable.customerRfqItemId, ids), eq(offerItemsTable.isApproved, true)));

  const byCustomerItem = new Map<number, number[]>();
  for (const row of linked) {
    if (row.customerRfqItemId == null) continue;
    const price = parseFloat(row.price);
    const excl = row.taxIncluded ? price / (1 + VAT_RATE) : price;
    const arr = byCustomerItem.get(row.customerRfqItemId) ?? [];
    arr.push(excl);
    byCustomerItem.set(row.customerRfqItemId, arr);
  }

  for (const ci of customerItems) {
    const approved = byCustomerItem.get(ci.id);
    if (approved && approved.length > 0) {
      result.set(ci.id, Math.min(...approved));
      continue;
    }
    // Fallback: match by partNo (priority) or lineItem for legacy rfq_items
    // that have no customer_rfq_item_id link.
    const key = ci.partNo?.trim() || ci.lineItem?.trim();
    if (!key) {
      result.set(ci.id, null);
      continue;
    }
    const partMatch = ci.partNo?.trim()
      ? eq(rfqItemsTable.partNo, ci.partNo.trim())
      : null;
    const lineMatch = ci.lineItem?.trim()
      ? eq(rfqItemsTable.lineItem, ci.lineItem.trim())
      : null;
    const matchCond = partMatch && lineMatch ? or(partMatch, lineMatch) : partMatch ?? lineMatch;
    if (!matchCond) {
      result.set(ci.id, null);
      continue;
    }
    const fallback = await db
      .select({ price: offerItemsTable.price, taxIncluded: offerItemsTable.taxIncluded })
      .from(offerItemsTable)
      .innerJoin(rfqItemsTable, eq(offerItemsTable.rfqItemId, rfqItemsTable.id))
      .where(and(matchCond, isNull(rfqItemsTable.customerRfqItemId), eq(offerItemsTable.isApproved, true)));
    if (fallback.length > 0) {
      const excl = fallback.map((f) =>
        f.taxIncluded ? parseFloat(f.price) / (1 + VAT_RATE) : parseFloat(f.price),
      );
      result.set(ci.id, Math.min(...excl));
    } else {
      result.set(ci.id, null);
    }
  }
  return result;
}

// Generate internal customer-RFQ number: CRFQ-YYYY-NNNNNN
async function generateInternalNo(): Promise<string> {
  const year = new Date().getFullYear();
  const [result] = await db.select({ cnt: count() }).from(customerRfqsTable);
  const seq = String((result?.cnt ?? 0) + 1).padStart(6, "0");
  return `CRFQ-${year}-${seq}`;
}

// Trim trailing zeros from a NUMERIC qty so "3.0000" reads as "3", "3.5000" as "3.5".
function formatQty(qty: string | null): string | null {
  if (qty == null) return null;
  const s = String(qty);
  if (!s.includes(".")) return s;
  const trimmed = s.replace(/0+$/, "").replace(/\.$/, "");
  return trimmed === "" ? "0" : trimmed;
}

// Line total = qty * unitPrice, rounded to 4dp and stripped of trailing zeros.
function computeTotal(qty: string | null, unitPrice: string | null): string | null {
  if (qty == null || unitPrice == null) return null;
  const q = Number(qty);
  const p = Number(unitPrice);
  if (!isFinite(q) || !isFinite(p)) return null;
  const n = Math.round(q * p * 10000) / 10000;
  return formatQty(String(n));
}

function serialize(r: typeof customerRfqsTable.$inferSelect, itemCount: number) {
  return {
    id: r.id,
    internalNo: r.internalNo,
    customerId: r.customerId,
    customerName: r.customerName,
    customerRfqNo: r.customerRfqNo,
    numberAutoGenerated: r.numberAutoGenerated,
    entryDate: r.entryDate,
    expiryDate: r.expiryDate,
    buyerName: r.buyerName,
    employeeId: r.employeeId,
    employeeName: r.employeeName,
    status: r.status,
    notes: r.notes,
    itemCount,
    createdAt: r.createdAt.toISOString(),
    updatedAt: r.updatedAt.toISOString(),
  };
}

// GET /customer-rfq — list with optional search
router.get("/customer-rfq", requireAuth, async (req, res): Promise<void> => {
  const { search, status } = req.query as Record<string, string>;

  const rows = await db
    .select({ rfq: customerRfqsTable })
    .from(customerRfqsTable)
    .orderBy(desc(customerRfqsTable.createdAt));

  let filtered = rows;
  if (status) filtered = filtered.filter((r) => r.rfq.status === status);
  if (search) {
    const s = search.toLowerCase();
    filtered = filtered.filter(
      (r) =>
        r.rfq.internalNo.toLowerCase().includes(s) ||
        r.rfq.customerRfqNo.toLowerCase().includes(s) ||
        r.rfq.customerName.toLowerCase().includes(s),
    );
  }

  const ids = filtered.map((r) => r.rfq.id);
  const counts =
    ids.length > 0
      ? await db
          .select({ customerRfqId: customerRfqItemsTable.customerRfqId, cnt: count() })
          .from(customerRfqItemsTable)
          .where(inArray(customerRfqItemsTable.customerRfqId, ids))
          .groupBy(customerRfqItemsTable.customerRfqId)
      : [];
  const countMap = Object.fromEntries(counts.map((c) => [c.customerRfqId, c.cnt]));

  res.json(filtered.map((r) => serialize(r.rfq, countMap[r.rfq.id] ?? 0)));
});

// GET /customer-rfq/numbers — all customer RFQ numbers (for the supplier-RFQ
// import combobox). Lets users pick a DB customer RFQ number instead of only
// Google-Sheet numbers; the lookup endpoint then fetches its items (DB first,
// sheet fallback).
router.get("/customer-rfq/numbers", requireAuth, async (_req, res): Promise<void> => {
  const rows = await db
    .select({ customerRfqNo: customerRfqsTable.customerRfqNo })
    .from(customerRfqsTable)
    .orderBy(desc(customerRfqsTable.createdAt));
  res.json({ rfqNumbers: rows.map((r) => r.customerRfqNo) });
});

// POST /customer-rfq — create a customer RFQ
router.post("/customer-rfq", requireAuth, async (req, res): Promise<void> => {
  const {
    customerId,
    customerName,
    customerRfqNo,
    entryDate,
    expiryDate,
    buyerName,
    notes,
    items,
  } = req.body as {
    customerId?: number | null;
    customerName?: string;
    customerRfqNo?: string;
    entryDate?: string;
    expiryDate?: string;
    buyerName?: string;
    notes?: string;
    items?: Array<{
      partNo?: string;
      lineItem?: string;
      description?: string;
      uom?: string;
      qty?: string | number | null;
      unitPrice?: string | number | null;
    }>;
  };

  if (!customerName?.trim()) {
    res.status(400).json({ error: "اسم العميل مطلوب" });
    return;
  }

  // Resolve customerId when the user picked a known customer but didn't pass the id.
  let resolvedCustomerId = customerId ?? null;
  if (!resolvedCustomerId) {
    const [match] = await db
      .select({ id: customersTable.id })
      .from(customersTable)
      .where(ilike(customersTable.name, customerName.trim()))
      .limit(1);
    if (match) resolvedCustomerId = match.id;
  }

  // Auto-generate the customer RFQ number when left empty.
  let finalRfqNo = customerRfqNo?.trim() ?? "";
  const autoGenerated = finalRfqNo === "";
  if (autoGenerated) {
    finalRfqNo = await generateInternalNo();
  }

  const internalNo = await generateInternalNo();

  // Resolve the creating employee's name (auto from the logged-in session).
  let employeeName: string | null = null;
  if (req.session.employeeId) {
    const [emp] = await db
      .select({ name: employeesTable.name })
      .from(employeesTable)
      .where(eq(employeesTable.id, req.session.employeeId));
    employeeName = emp?.name ?? null;
  }

  const [rfq] = await db
    .insert(customerRfqsTable)
    .values({
      internalNo,
      customerId: resolvedCustomerId,
      customerName: customerName.trim(),
      customerRfqNo: finalRfqNo,
      numberAutoGenerated: autoGenerated,
      entryDate: entryDate || null,
      expiryDate: expiryDate || null,
      buyerName: buyerName?.trim() || null,
      employeeId: req.session.employeeId ?? null,
      employeeName,
      status: "draft",
      notes: notes?.trim() || null,
    })
    .returning();

  let itemCount = 0;
  if (items && items.length > 0) {
    const validItems = items.filter((it) => (it.partNo?.trim() || it.lineItem?.trim()) && it.qty);
    if (validItems.length > 0) {
      await db.insert(customerRfqItemsTable).values(
        validItems.map((it) => ({
          customerRfqId: rfq.id,
          partNo: it.partNo?.trim() || null,
          // lineItem must contain no spaces — strip them automatically.
          lineItem: it.lineItem ? it.lineItem.replace(/\s+/g, "") : null,
          description: it.description?.trim() || null,
          uom: it.uom?.trim() || null,
          qty: it.qty != null && it.qty !== "" ? String(it.qty) : null,
          unitPrice: it.unitPrice != null && it.unitPrice !== "" ? String(it.unitPrice) : null,
        })),
      );
      itemCount = validItems.length;
    }
  }

  await db.insert(auditLogTable).values({
    action: "customer_rfq.created",
    entityType: "customer_rfq",
    entityId: rfq.id,
    employeeId: req.session.employeeId,
    description: `Created customer RFQ ${internalNo} for ${customerName.trim()}${
      autoGenerated ? ` (number auto-generated: ${finalRfqNo})` : ""
    } with ${itemCount} item(s)`,
    ipAddress: req.ip,
    userAgent: req.get("user-agent"),
  });

  res.status(201).json({ ...serialize(rfq, itemCount) });
});

// GET /customer-rfq/:id — single with items
router.get("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [row] = await db
    .select({ rfq: customerRfqsTable })
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  if (!row) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const items = await db
    .select()
    .from(customerRfqItemsTable)
    .where(eq(customerRfqItemsTable.customerRfqId, id));
  res.json({
    ...serialize(row.rfq, items.length),
    items: items.map((i) => ({
      id: i.id,
      customerRfqId: i.customerRfqId,
      partNo: i.partNo,
      lineItem: i.lineItem,
      description: i.description,
      uom: i.uom,
      qty: formatQty(i.qty),
      unitPrice: formatQty(i.unitPrice),
      total: computeTotal(i.qty, i.unitPrice),
      createdAt: i.createdAt.toISOString(),
    })),
  });
});

// PATCH /customer-rfq/:id — update a draft
router.patch("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [existing] = await db
    .select()
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  if (!existing) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  if (existing.status !== "draft") {
    res.status(400).json({ error: "لا يمكن تعديل طلب تسعير العميل بعد إرساله" });
    return;
  }

  const { customerName, customerRfqNo, entryDate, expiryDate, buyerName, notes, status, items, overrideMarginCheck } =
    req.body as {
      customerName?: string;
      customerRfqNo?: string;
      entryDate?: string;
      expiryDate?: string;
      buyerName?: string;
      notes?: string;
      status?: string;
      items?: Array<{
        partNo?: string;
        lineItem?: string;
        description?: string;
        uom?: string;
        qty?: string | number | null;
        unitPrice?: string | number | null;
      }>;
      overrideMarginCheck?: boolean;
    };

  const updates: Record<string, unknown> = {};
  if (customerName !== undefined) updates.customerName = customerName.trim();
  if (customerRfqNo !== undefined) {
    const trimmed = customerRfqNo.trim();
    if (trimmed === "") {
      // Number cleared on edit — regenerate an auto number and (re)flag it.
      updates.customerRfqNo = await generateInternalNo();
      updates.numberAutoGenerated = true;
    } else {
      updates.customerRfqNo = trimmed;
      updates.numberAutoGenerated = false;
    }
  }
  if (entryDate !== undefined) updates.entryDate = entryDate || null;
  if (expiryDate !== undefined) updates.expiryDate = expiryDate || null;
  if (buyerName !== undefined) updates.buyerName = buyerName?.trim() || null;
  if (notes !== undefined) updates.notes = notes?.trim() || null;

  // Finalizing (status → sent) requires every item to have a price, and every
  // priced item to clear the margin check against the approved supplier price.
  const validItems = items
    ? items.filter((it) => (it.partNo?.trim() || it.lineItem?.trim()) && it.qty)
    : undefined;
  if (status === "sent" && validItems !== undefined) {
    const unpriced = validItems.filter((it) => it.unitPrice == null || it.unitPrice === "" || Number(it.unitPrice) <= 0);
    if (unpriced.length > 0) {
      res.status(400).json({ error: "أدخل سعر كل بند قبل تثبيت الطلب" });
      return;
    }

    // Margin check: each customer price (excl tax) must be ≥ 1.06 × the
    // approved supplier price (excl tax) for the matching item. The approved
    // cost is resolved via the customer_rfq_item_id link on rfq_items, with a
    // partNo/lineItem fallback for legacy supplier RFQs. An admin may override
    // (with audit logging); non-admins are blocked.
    const isAdmin = req.session.role === "admin";
    const overriding = overrideMarginCheck === true && isAdmin;

    // Current DB items carry the original ids that rfq_items link to (the
    // delete+recreate below would invalidate those ids, so resolve first).
    const currentDbItems = await db
      .select({ id: customerRfqItemsTable.id, partNo: customerRfqItemsTable.partNo, lineItem: customerRfqItemsTable.lineItem })
      .from(customerRfqItemsTable)
      .where(eq(customerRfqItemsTable.customerRfqId, id));
    const costs = await resolveApprovedCosts(currentDbItems);

    // Map a req.body item to its current DB item id by partNo (priority) then lineItem.
    const findDbId = (it: { partNo?: string; lineItem?: string }): number | null => {
      const p = it.partNo?.trim();
      const l = it.lineItem?.trim();
      if (p) {
        const m = currentDbItems.find((d) => (d.partNo ?? "").trim() === p);
        if (m) return m.id;
      }
      if (l) {
        const m = currentDbItems.find((d) => (d.lineItem ?? "").trim() === l);
        if (m) return m.id;
      }
      return null;
    };

    const violations: string[] = [];
    for (const it of validItems) {
      const dbId = findDbId(it);
      const cost = dbId != null ? (costs.get(dbId) ?? null) : null;
      const customerPrice = Number(it.unitPrice);
      if (cost == null) {
        violations.push(`لا يوجد سعر مورد معتمد للبند (${it.partNo || it.lineItem})`);
      } else if (customerPrice < cost * MARGIN_FACTOR) {
        const minRequired = cost * MARGIN_FACTOR;
        violations.push(
          `سعر البند (${it.partNo || it.lineItem}) ${customerPrice.toFixed(2)} أقل من الحد الأدنى ${minRequired.toFixed(2)} (سعر المورد المعتمد ${cost.toFixed(2)} × 1.06)`,
        );
      }
    }

    if (violations.length > 0 && !overriding) {
      res.status(400).json({
        error: "تعذّر تثبيت الطلب: " + violations.join(" — "),
        marginViolations: violations,
      });
      return;
    }

    if (violations.length > 0 && overriding) {
      await db.insert(auditLogTable).values({
        action: "customer_rfq.margin_override",
        entityType: "customer_rfq",
        entityId: id,
        employeeId: req.session.employeeId,
        description: `Admin overrode margin check on finalize: ${violations.join(" | ")}`,
        ipAddress: req.ip,
        userAgent: req.get("user-agent"),
      });
    }

    updates.status = "sent";
  } else if (status !== undefined) {
    updates.status = status;
  }

  if (Object.keys(updates).length > 0) {
    await db.update(customerRfqsTable).set(updates).where(eq(customerRfqsTable.id, id));
  }

  if (items !== undefined) {
    await db.delete(customerRfqItemsTable).where(eq(customerRfqItemsTable.customerRfqId, id));
    if (validItems && validItems.length > 0) {
      await db.insert(customerRfqItemsTable).values(
        validItems.map((it) => ({
          customerRfqId: id,
          partNo: it.partNo?.trim() || null,
          lineItem: it.lineItem ? it.lineItem.replace(/\s+/g, "") : null,
          description: it.description?.trim() || null,
          uom: it.uom?.trim() || null,
          qty: it.qty != null && it.qty !== "" ? String(it.qty) : null,
          unitPrice: it.unitPrice != null && it.unitPrice !== "" ? String(it.unitPrice) : null,
        })),
      );
    }
  }

  const [updated] = await db
    .select()
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  const itemRows = await db
    .select()
    .from(customerRfqItemsTable)
    .where(eq(customerRfqItemsTable.customerRfqId, id));
  res.json({
    ...serialize(updated, itemRows.length),
    items: itemRows.map((i) => ({
      id: i.id,
      customerRfqId: i.customerRfqId,
      partNo: i.partNo,
      lineItem: i.lineItem,
      description: i.description,
      uom: i.uom,
      qty: formatQty(i.qty),
      unitPrice: formatQty(i.unitPrice),
      total: computeTotal(i.qty, i.unitPrice),
      createdAt: i.createdAt.toISOString(),
    })),
  });
});

// DELETE /customer-rfq/:id
router.delete("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [deleted] = await db
    .delete(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id))
    .returning();
  if (!deleted) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  res.status(204).end();
});

export default router;
