import { Router } from "express";
import {
  db,
  customerRfqsTable,
  customerRfqItemsTable,
  customersTable,
  auditLogTable,
} from "@workspace/db";
import { eq, ilike, count, inArray, desc } from "drizzle-orm";
import { requireAuth } from "../../middlewares/auth";

const router = Router();

// Generate internal customer-RFQ number: CRFQ-YYYY-NNNNNN
async function generateInternalNo(): Promise<string> {
  const year = new Date().getFullYear();
  const [result] = await db.select({ cnt: count() }).from(customerRfqsTable);
  const seq = String((result?.cnt ?? 0) + 1).padStart(6, "0");
  return `CRFQ-${year}-${seq}`;
}

function serialize(r: typeof customerRfqsTable.$inferSelect, itemCount: number) {
  return {
    id: r.id,
    internalNo: r.internalNo,
    customerId: r.customerId,
    customerName: r.customerName,
    customerRfqNo: r.customerRfqNo,
    numberAutoGenerated: r.numberAutoGenerated,
    entryDate: r.entryDate,
    expiryDate: r.expiryDate,
    buyerName: r.buyerName,
    status: r.status,
    notes: r.notes,
    itemCount,
    createdAt: r.createdAt.toISOString(),
    updatedAt: r.updatedAt.toISOString(),
  };
}

// GET /customer-rfq — list with optional search
router.get("/customer-rfq", requireAuth, async (req, res): Promise<void> => {
  const { search, status } = req.query as Record<string, string>;

  const rows = await db
    .select({ rfq: customerRfqsTable })
    .from(customerRfqsTable)
    .orderBy(desc(customerRfqsTable.createdAt));

  let filtered = rows;
  if (status) filtered = filtered.filter((r) => r.rfq.status === status);
  if (search) {
    const s = search.toLowerCase();
    filtered = filtered.filter(
      (r) =>
        r.rfq.internalNo.toLowerCase().includes(s) ||
        r.rfq.customerRfqNo.toLowerCase().includes(s) ||
        r.rfq.customerName.toLowerCase().includes(s),
    );
  }

  const ids = filtered.map((r) => r.rfq.id);
  const counts =
    ids.length > 0
      ? await db
          .select({ customerRfqId: customerRfqItemsTable.customerRfqId, cnt: count() })
          .from(customerRfqItemsTable)
          .where(inArray(customerRfqItemsTable.customerRfqId, ids))
          .groupBy(customerRfqItemsTable.customerRfqId)
      : [];
  const countMap = Object.fromEntries(counts.map((c) => [c.customerRfqId, c.cnt]));

  res.json(filtered.map((r) => serialize(r.rfq, countMap[r.rfq.id] ?? 0)));
});

// POST /customer-rfq — create a customer RFQ
router.post("/customer-rfq", requireAuth, async (req, res): Promise<void> => {
  const {
    customerId,
    customerName,
    customerRfqNo,
    entryDate,
    expiryDate,
    buyerName,
    notes,
    items,
  } = req.body as {
    customerId?: number | null;
    customerName?: string;
    customerRfqNo?: string;
    entryDate?: string;
    expiryDate?: string;
    buyerName?: string;
    notes?: string;
    items?: Array<{
      partNo?: string;
      lineItem?: string;
      uom?: string;
      qty?: string | number | null;
    }>;
  };

  if (!customerName?.trim()) {
    res.status(400).json({ error: "اسم العميل مطلوب" });
    return;
  }

  // Resolve customerId when the user picked a known customer but didn't pass the id.
  let resolvedCustomerId = customerId ?? null;
  if (!resolvedCustomerId) {
    const [match] = await db
      .select({ id: customersTable.id })
      .from(customersTable)
      .where(ilike(customersTable.name, customerName.trim()))
      .limit(1);
    if (match) resolvedCustomerId = match.id;
  }

  // Auto-generate the customer RFQ number when left empty.
  let finalRfqNo = customerRfqNo?.trim() ?? "";
  const autoGenerated = finalRfqNo === "";
  if (autoGenerated) {
    finalRfqNo = await generateInternalNo();
  }

  const internalNo = await generateInternalNo();

  const [rfq] = await db
    .insert(customerRfqsTable)
    .values({
      internalNo,
      customerId: resolvedCustomerId,
      customerName: customerName.trim(),
      customerRfqNo: finalRfqNo,
      numberAutoGenerated: autoGenerated,
      entryDate: entryDate || null,
      expiryDate: expiryDate || null,
      buyerName: buyerName?.trim() || null,
      status: "draft",
      notes: notes?.trim() || null,
    })
    .returning();

  let itemCount = 0;
  if (items && items.length > 0) {
    const validItems = items.filter((it) => (it.partNo?.trim() || it.lineItem?.trim()) && it.qty);
    if (validItems.length > 0) {
      await db.insert(customerRfqItemsTable).values(
        validItems.map((it) => ({
          customerRfqId: rfq.id,
          partNo: it.partNo?.trim() || null,
          // lineItem must contain no spaces — strip them automatically.
          lineItem: it.lineItem ? it.lineItem.replace(/\s+/g, "") : null,
          uom: it.uom?.trim() || null,
          qty: it.qty != null && it.qty !== "" ? String(it.qty) : null,
        })),
      );
      itemCount = validItems.length;
    }
  }

  await db.insert(auditLogTable).values({
    action: "customer_rfq.created",
    entityType: "customer_rfq",
    entityId: rfq.id,
    employeeId: req.session.employeeId,
    description: `Created customer RFQ ${internalNo} for ${customerName.trim()}${
      autoGenerated ? ` (number auto-generated: ${finalRfqNo})` : ""
    } with ${itemCount} item(s)`,
    ipAddress: req.ip,
    userAgent: req.get("user-agent"),
  });

  res.status(201).json({ ...serialize(rfq, itemCount) });
});

// GET /customer-rfq/:id — single with items
router.get("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [row] = await db
    .select({ rfq: customerRfqsTable })
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  if (!row) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const items = await db
    .select()
    .from(customerRfqItemsTable)
    .where(eq(customerRfqItemsTable.customerRfqId, id));
  res.json({
    ...serialize(row.rfq, items.length),
    items: items.map((i) => ({
      id: i.id,
      customerRfqId: i.customerRfqId,
      partNo: i.partNo,
      lineItem: i.lineItem,
      uom: i.uom,
      qty: i.qty,
      createdAt: i.createdAt.toISOString(),
    })),
  });
});

// PATCH /customer-rfq/:id — update a draft
router.patch("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [existing] = await db
    .select()
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  if (!existing) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  if (existing.status !== "draft") {
    res.status(400).json({ error: "لا يمكن تعديل طلب تسعير العميل بعد إرساله" });
    return;
  }

  const { customerName, customerRfqNo, entryDate, expiryDate, buyerName, notes, status, items } =
    req.body as {
      customerName?: string;
      customerRfqNo?: string;
      entryDate?: string;
      expiryDate?: string;
      buyerName?: string;
      notes?: string;
      status?: string;
      items?: Array<{
        partNo?: string;
        lineItem?: string;
        uom?: string;
        qty?: string | number | null;
      }>;
    };

  const updates: Record<string, unknown> = {};
  if (customerName !== undefined) updates.customerName = customerName.trim();
  if (customerRfqNo !== undefined) updates.customerRfqNo = customerRfqNo.trim();
  if (entryDate !== undefined) updates.entryDate = entryDate || null;
  if (expiryDate !== undefined) updates.expiryDate = expiryDate || null;
  if (buyerName !== undefined) updates.buyerName = buyerName?.trim() || null;
  if (notes !== undefined) updates.notes = notes?.trim() || null;
  if (status !== undefined) updates.status = status;

  if (Object.keys(updates).length > 0) {
    await db.update(customerRfqsTable).set(updates).where(eq(customerRfqsTable.id, id));
  }

  if (items !== undefined) {
    await db.delete(customerRfqItemsTable).where(eq(customerRfqItemsTable.customerRfqId, id));
    const validItems = items.filter((it) => (it.partNo?.trim() || it.lineItem?.trim()) && it.qty);
    if (validItems.length > 0) {
      await db.insert(customerRfqItemsTable).values(
        validItems.map((it) => ({
          customerRfqId: id,
          partNo: it.partNo?.trim() || null,
          lineItem: it.lineItem ? it.lineItem.replace(/\s+/g, "") : null,
          uom: it.uom?.trim() || null,
          qty: it.qty != null && it.qty !== "" ? String(it.qty) : null,
        })),
      );
    }
  }

  const [updated] = await db
    .select()
    .from(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id));
  const itemRows = await db
    .select()
    .from(customerRfqItemsTable)
    .where(eq(customerRfqItemsTable.customerRfqId, id));
  res.json({
    ...serialize(updated, itemRows.length),
    items: itemRows.map((i) => ({
      id: i.id,
      customerRfqId: i.customerRfqId,
      partNo: i.partNo,
      lineItem: i.lineItem,
      uom: i.uom,
      qty: i.qty,
      createdAt: i.createdAt.toISOString(),
    })),
  });
});

// DELETE /customer-rfq/:id
router.delete("/customer-rfq/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  const [deleted] = await db
    .delete(customerRfqsTable)
    .where(eq(customerRfqsTable.id, id))
    .returning();
  if (!deleted) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  res.status(204).end();
});

export default router;
