import { describe, it, expect, vi, beforeAll, beforeEach } from "vitest";
import express from "express";
import request from "supertest";

// ── Mock auth ───────────────────────────────────────────────────────────────
vi.mock("../../middlewares/auth", () => ({
  requireAuth: (_req: any, _res: any, next: any) => next(),
}));

// ── Chainable + thenable DB mock ─────────────────────────────────────────────
function thenable<T>(value: T, extra: Record<string, any> = {}): any {
  const obj: any = { then: (resolve: any) => Promise.resolve(value).then(resolve) };
  for (const [k, v] of Object.entries(extra)) obj[k] = v;
  return obj;
}

// Tables referenced by .from() / eq() / .references() — truthy markers are enough.
const rfqTable = { _: "customerRfqs", createdAt: "createdAt", id: "id" };
const itemsTable = { _: "customerRfqItems", customerRfqId: "customerRfqId" };
const customersTable = { _: "customers", id: "id", name: "name" };
const auditTable = { _: "audit" };
const tables = {
  customerRfqsTable: rfqTable,
  customerRfqItemsTable: itemsTable,
  customersTable,
  auditLogTable: auditTable,
};

// Per-test state.
let listRows: any[];
let countRows: any[];
let countRow: { cnt: number };
let insertedRfq: any;
let detailRow: any | null;
let detailItems: any[];

// Tracks the exact values written to customer_rfq_items so we can assert the
// lineItem space-stripping behaviour.
const insertedItems: any[] = [];

// Build an object that is BOTH thenable (awaitable directly) and exposes chain
// methods. Each chain method returns a thenable of `value`.
function chainable(value: any, methods: Record<string, any> = {}): any {
  const obj: any = { then: (resolve: any) => Promise.resolve(value).then(resolve) };
  for (const [k, fn] of Object.entries(methods)) obj[k] = fn;
  return obj;
}

const dbMock: any = {
  // select() builds a chain whose .from(table) decides which data to return.
  select: vi.fn((arg?: any) => ({
    from: vi.fn((table: any) => {
      // generateInternalNo: select({cnt: count()}).from(rfqTable) — awaited directly.
      if (table === rfqTable && arg && typeof arg === "object" && "cnt" in arg) {
        return chainable([countRow]);
      }
      // rfq list/detail (select {rfq: ...} or bare select)
      if (table === rfqTable) {
        return chainable(detailRow ? [{ rfq: detailRow }] : [], {
          // list chains .orderBy; detail chains .where
          orderBy: vi.fn(() => chainable(listRows)),
          where: vi.fn(() => chainable(detailRow ? [{ rfq: detailRow }] : [])),
          limit: vi.fn(() => chainable(detailRow ? [{ rfq: detailRow }] : [])),
        });
      }
      // item-count aggregate for list: select({customerRfqId, cnt}).from(items).where().groupBy()
      if (table === itemsTable && arg && typeof arg === "object" && "cnt" in arg) {
        return chainable(countRows, {
          where: vi.fn(() => chainable(countRows, { groupBy: vi.fn(() => chainable(countRows)) })),
          groupBy: vi.fn(() => chainable(countRows)),
        });
      }
      // items list for detail (bare select).from(items).where()
      if (table === itemsTable) {
        return chainable(detailItems, {
          where: vi.fn(() => chainable(detailItems)),
        });
      }
      // customer name resolution (select {id}).from(customers).where().limit()
      return chainable([], {
        where: vi.fn(() => chainable([], { limit: vi.fn(() => chainable([])) })),
      });
    }),
  })),
  insert: vi.fn((table: any) => ({
    values: vi.fn((vals: any) => {
      if (table === itemsTable) {
        if (Array.isArray(vals)) insertedItems.push(...vals);
        else insertedItems.push(vals);
        return chainable(undefined);
      }
      // rfq insert: reflect the values the route passed (e.g. numberAutoGenerated)
      // merged over the default row so tests can assert server-computed fields.
      return {
        returning: vi.fn(() => chainable([{ ...insertedRfq, ...vals }])),
      };
    }),
  })),
  update: vi.fn(() => ({
    set: vi.fn(() => ({ where: vi.fn(() => chainable(undefined)) })),
  })),
  delete: vi.fn((table: any) => ({
    where: vi.fn(() => {
      if (table === rfqTable) return { returning: vi.fn(() => chainable(detailRow ? [detailRow] : [])) };
      return chainable(undefined);
    }),
  })),
};

vi.mock("@workspace/db", () => ({ ...tables, db: dbMock }));

let testApp: express.Express;

beforeAll(async () => {
  const { default: customerRfqRouter } = await import("../../modules/customer-rfq/index");
  testApp = express();
  testApp.use(express.json());
  testApp.use((req: any, _res: any, next: any) => {
    req.log = { error: () => {}, warn: () => {}, info: () => {}, debug: () => {} };
    req.session = { employeeId: 1 };
    next();
  });
  testApp.use("/api", customerRfqRouter);
});

beforeEach(() => {
  vi.clearAllMocks();
  listRows = [];
  countRows = [];
  countRow = { cnt: 5 };
  insertedRfq = {
    id: 42,
    internalNo: "CRFQ-2025-000042",
    customerId: null,
    customerName: "Acme",
    customerRfqNo: "CUST-001",
    numberAutoGenerated: false,
    entryDate: null,
    expiryDate: null,
    buyerName: null,
    status: "draft",
    notes: null,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-02"),
  };
  detailRow = null;
  detailItems = [];
  insertedItems.length = 0;
});

describe("POST /api/customer-rfq (create)", () => {
  it("auto-generates the customer RFQ number when blank and flags it", async () => {
    const res = await request(testApp).post("/api/customer-rfq").send({
      customerName: "Acme",
      customerRfqNo: "",
      items: [{ partNo: "P1", lineItem: "AB CD", uom: "pc", qty: 5 }],
    });
    expect(res.status).toBe(201);
    expect(res.body.numberAutoGenerated).toBe(true);
    expect(res.body.customerRfqNo).toMatch(/^CRFQ-\d{4}-/);
  });

  it("keeps the user-provided number and does not flag auto-generation", async () => {
    const res = await request(testApp).post("/api/customer-rfq").send({
      customerName: "Acme",
      customerRfqNo: "RFQ-99",
      items: [{ partNo: "P1", lineItem: "AB CD", uom: "pc", qty: 5 }],
    });
    expect(res.status).toBe(201);
    expect(res.body.numberAutoGenerated).toBe(false);
    expect(res.body.customerRfqNo).toBe("RFQ-99");
  });

  it("strips all spaces from lineItem before saving", async () => {
    await request(testApp).post("/api/customer-rfq").send({
      customerName: "Acme",
      customerRfqNo: "RFQ-1",
      items: [{ partNo: "P1", lineItem: "A B  C D", uom: "pc", qty: 2 }],
    });
    expect(insertedItems).toHaveLength(1);
    expect(insertedItems[0].lineItem).toBe("ABCD");
  });

  it("persists the line-item description", async () => {
    await request(testApp).post("/api/customer-rfq").send({
      customerName: "Acme",
      customerRfqNo: "RFQ-2",
      items: [{ partNo: "P1", lineItem: "AB", description: "  وصف البند  ", uom: "pc", qty: 1 }],
    });
    expect(insertedItems).toHaveLength(1);
    expect(insertedItems[0].description).toBe("وصف البند");
  });

  it("returns 400 when customerName is missing", async () => {
    const res = await request(testApp).post("/api/customer-rfq").send({ customerRfqNo: "X" });
    expect(res.status).toBe(400);
  });
});

describe("GET /api/customer-rfq (list)", () => {
  it("returns the list with item counts", async () => {
    listRows = [{ rfq: { ...insertedRfq, id: 1, internalNo: "CRFQ-1", itemCount: undefined } }];
    countRows = [{ customerRfqId: 1, cnt: 3 }];
    const res = await request(testApp).get("/api/customer-rfq");
    expect(res.status).toBe(200);
    expect(res.body[0].internalNo).toBe("CRFQ-1");
    expect(res.body[0].itemCount).toBe(3);
  });
});

describe("GET /api/customer-rfq/:id", () => {
  it("returns 404 when not found", async () => {
    detailRow = null;
    const res = await request(testApp).get("/api/customer-rfq/999");
    expect(res.status).toBe(404);
  });

  it("returns the rfq with items when found", async () => {
    detailRow = insertedRfq;
    detailItems = [
      { id: 1, customerRfqId: 42, partNo: "P1", lineItem: "ABCD", description: "وصف البند", uom: "pc", qty: "5", createdAt: new Date("2025-01-01") },
    ];
    const res = await request(testApp).get("/api/customer-rfq/42");
    expect(res.status).toBe(200);
    expect(res.body.id).toBe(42);
    expect(res.body.items).toHaveLength(1);
    expect(res.body.items[0].lineItem).toBe("ABCD");
    expect(res.body.items[0].description).toBe("وصف البند");
  });
});

describe("DELETE /api/customer-rfq/:id", () => {
  it("returns 204 when deleted", async () => {
    detailRow = insertedRfq;
    const res = await request(testApp).delete("/api/customer-rfq/42");
    expect(res.status).toBe(204);
  });

  it("returns 404 when not found", async () => {
    detailRow = null;
    const res = await request(testApp).delete("/api/customer-rfq/999");
    expect(res.status).toBe(404);
  });
});
