import { pgTable, text, serial, timestamp, integer, numeric, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { customersTable } from "./customers";

// طلب تسعير العميل — Customer Request for Quotation
export const customerRfqsTable = pgTable("customer_rfqs", {
  id: serial("id").primaryKey(),
  internalNo: text("internal_no").notNull().unique(),
  customerId: integer("customer_id").references(() => customersTable.id),
  customerName: text("customer_name").notNull(),
  customerRfqNo: text("customer_rfq_no").notNull(),
  numberAutoGenerated: boolean("number_auto_generated").notNull().default(false),
  entryDate: text("entry_date"),
  expiryDate: text("expiry_date"),
  buyerName: text("buyer_name"),
  status: text("status").notNull().default("draft"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const customerRfqItemsTable = pgTable("customer_rfq_items", {
  id: serial("id").primaryKey(),
  customerRfqId: integer("customer_rfq_id")
    .notNull()
    .references(() => customerRfqsTable.id, { onDelete: "cascade" }),
  partNo: text("part_no"),
  lineItem: text("line_item"),
  uom: text("uom"),
  qty: numeric("qty", { precision: 15, scale: 4 }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertCustomerRfqSchema = createInsertSchema(customerRfqsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertCustomerRfq = z.infer<typeof insertCustomerRfqSchema>;
export type CustomerRfq = typeof customerRfqsTable.$inferSelect;

export const insertCustomerRfqItemSchema = createInsertSchema(customerRfqItemsTable).omit({
  id: true,
  createdAt: true,
});
export type InsertCustomerRfqItem = z.infer<typeof insertCustomerRfqItemSchema>;
export type CustomerRfqItem = typeof customerRfqItemsTable.$inferSelect;
